/* Generated by scripts/build-landing.sh - do not edit by hand, edit web/landing/src/config.js
   and the environment variables passed to the build instead. */
window.TATAZO_CONFIG = {
  SUPABASE_URL: "",
  SUPABASE_ANON_KEY: "",
  WIKI_URL: "https://wiki.playtatazo.online/",
  FORUM_URL: "https://forum.playtatazo.online/",
  SITE_URL: "https://playtatazo.online/"
};
